const q = value => JSON.stringify(String(value));
const commands = [];
const add = (type,id,attrs) => commands.push(`+${type} ${id} ${Object.entries(attrs).map(([k,v])=>`${k}=${q(v)}`).join(' ')};`);
const set = (id,attrs) => commands.push(`SET ${id} ${Object.entries(attrs).map(([k,v])=>`${k}=${q(v)}`).join(' ')};`);
const frame = (id,parent,attrs={}) => add('FrameNode',id,{name:id,parent,layout:'stack',stackDirection:'vertical',stackAlignment:'start',stackDistribution:'start',width:'1fr',height:'auto',overflow:'clip',position:'relative',...attrs});
const text = (id,parent,copy,attrs={}) => add('RichTextNode',id,{name:id,parent,text:copy,fontName:'Geist',fontWeight:400,fontSize:'16px',lineHeight:'1.5em',textColor:'#424242',width:'1fr',height:'auto',position:'relative',...attrs});
const icon = (id,parent,name,attrs={}) => add('IconNode',id,{parent,set:'Lucide',$control__icon:name,$control__color:'#424242',$control__width:1.5,width:'18px',height:'18px',position:'relative',...attrs});
const link = (id,parent,title,url,attrs={}) => {frame(id,parent,{width:'auto',padding:'10px 4px',stackDirection:'horizontal',stackAlignment:'center',gap:'6px','link.href':url,...attrs}); text(id+'Label',id,title,{width:'auto',fontSize:'14px',fontWeight:500,linkStylePreset:'zinepsLink'});};
const button = (id,parent,title,url,primary=true) => {frame(id,parent,{width:'auto',padding:'15px 22px',radius:'7px',fill:primary?'#70CAB9':'#FFFFFF',border:primary?'1px solid #70CAB9':'1px solid #DCE5E2',stackDirection:'horizontal',stackAlignment:'center',gap:'12px','link.href':url,'hoverEffect.opacity':0.86,'hoverEffect.transition':'tween 0.2s'}); text(id+'Label',id,title,{width:'auto',fontWeight:600,fontSize:'15px',textColor:'#173B35'});};
set('WQLkyLRf1',{layout:'stack',stackDirection:'vertical',stackAlignment:'center',stackDistribution:'start',height:'auto',width:'1440px',fill:'#FFFFFF',gap:'0px',overflow:'clip'});
add('LinkStylePresetNode','zinepsLink',{name:'Zineps / Navigation','link.textColor':'#424242','link.hover.textColor':'#177A69','link.transition':'tween 0.2s'});
add('ComponentNode','zinepsNav',{name:'Zineps / Navigation'});
frame('navDesktop','zinepsNav',{name:'Desktop',width:'1440px',fill:'#FFFFFF',stackAlignment:'center',overflow:'visible',padding:'0px 64px'});
frame('navRow','navDesktop',{name:'Navigation bar',maxWidth:'1312px',height:'88px',stackDirection:'horizontal',stackAlignment:'center',stackDistribution:'space-between',overflow:'visible'});
frame('brand','navRow',{name:'Zineps original logo',width:'118px',height:'38px',fill:'https://www.zineps.com/_next/static/media/Group.4de5c46a.svg',altText:'Zineps','link.href':'/'});
frame('navLinks','navRow',{width:'auto',stackDirection:'horizontal',stackAlignment:'center',gap:'24px',overflow:'visible'});
const dropdown=(id,title,items)=>{frame(id,'navLinks',{width:'auto',stackDirection:'horizontal',stackAlignment:'center',gap:'6px',padding:'10px 4px',overflow:'visible',htmlTag:'button',ariaLabel:title,'onMouseEnter.0.action':'SHOW_OVERLAY','onMouseEnter.0.controls.overlay':id+'Overlay','onTap.0.action':'SHOW_OVERLAY','onTap.0.controls.overlay':id+'Overlay'});text(id+'Label',id,title,{width:'auto',fontSize:'14px',fontWeight:500});icon(id+'Chevron',id,'Chevron Down',{width:'14px',height:'14px'});add('RelativeOverlayNode',id+'Overlay',{parent:id,name:title+' menu',layout:'stack',stackDirection:'vertical',stackAlignment:'start',gap:'4px',width:'290px',height:'auto',padding:'12px',fill:'#FFFFFF',border:'1px solid #E4EAE7',radius:'8px',floatingPlacement:'bottom',floatingAlignment:'start',floatingOffsetY:'12px',floatingCollisionDetection:true,floatingCollisionPadding:'16px','boxShadows.0':'0px 12px 30px 0px rgba(30,65,57,0.10)'});items.forEach(([label,url],i)=>link(id+'Sub'+i,id+'Overlay',label,url,{width:'1fr',padding:'12px'}));};
dropdown('products','Products',[['E-commerce shipping','https://www.zineps.com/shipping'],['For logistics partners','https://www.zineps.com/logistics-operating-system'],['Shipping AI','https://www.zineps.com/ai-shipping-intelligence']]);
link('integrations','navLinks','Integrations','https://www.zineps.com/integrations');
link('pricing','navLinks','Pricing','https://www.zineps.com/pricing');
link('blog','navLinks','Blog','https://www.zineps.com/blog/');
dropdown('knowledge','Knowledge Base',[['Overview','https://www.zineps.com/knowledge-base']]);
frame('navActions','navRow',{width:'auto',stackDirection:'horizontal',stackAlignment:'center',gap:'16px'});
button('navCta','navActions','Start shipping','https://app.zineps.com/Account/Register');
frame('menuToggle','navActions',{width:'44px',height:'44px',padding:'10px',visible:false,htmlTag:'button',ariaLabel:'Open navigation menu',stackAlignment:'center',stackDistribution:'center','onTap.0.action':'SET_VARIANT','onTap.0.controls.variant':'navPhoneOpen'});icon('menuGlyph','menuToggle','Menu',{width:'22px',height:'22px'});
frame('mobileLinks','navDesktop',{visible:false,padding:'8px 0px 24px',gap:'4px'});
[['E-commerce shipping','/shipping'],['Logistics partners','/logistics-operating-system'],['Shipping AI','/ai-shipping-intelligence'],['Integrations','/integrations'],['Pricing','/pricing'],['Blog','/blog/'],['Knowledge Base','/knowledge-base']].forEach(([label,path],i)=>link('mobileLink'+i,'mobileLinks',label,'https://www.zineps.com'+path,{width:'1fr',padding:'12px 4px'}));
commands.push('CREATE_VARIANT navPhone from="navDesktop";');
set('navPhone',{name:'Phone',width:'390px',height:'72px',padding:'0px 24px',overflow:'clip',left:'1600px'});
set('navPhonenavRow',{height:'72px'});set('navPhonenavLinks',{visible:false});set('navPhonemenuToggle',{visible:true});set('navPhonemobileLinks',{visible:true});set('navPhonenavCta',{visible:false});
commands.push('CREATE_VARIANT navPhoneOpen from="navPhone";');set('navPhoneOpen',{name:'Phone Open',height:'auto',left:'2090px'});set('navPhoneOpenmenuToggle',{'onTap.0.action':'SET_VARIANT','onTap.0.controls.variant':'navPhone',ariaLabel:'Close navigation menu'});set('navPhoneOpenmenuGlyph',{$control__icon:'X'});
frame('hero','WQLkyLRf1',{name:'Hero — shipping infrastructure',maxWidth:'1440px',width:'1fr',padding:'104px 64px 100px',stackDirection:'horizontal',stackAlignment:'center',gap:'64px',overflow:'visible'});
frame('heroCopy','hero',{name:'Message and actions',width:'470px',gap:'28px',overflow:'visible'});
frame('eyebrow','heroCopy',{width:'auto',stackDirection:'horizontal',stackAlignment:'center',gap:'10px'});frame('eyebrowDot','eyebrow',{width:'6px',height:'6px',radius:'100px',fill:'#70CAB9'});text('eyebrowLabel','eyebrow','BUILT FOR BUSINESSES THAT SHIP',{width:'auto',fontSize:'11px',fontWeight:600,letterSpacing:'1.4px',textColor:'#42675E'});
text('headline','heroCopy','Your shipping. One intelligent platform.',{tag:'h1',fontSize:'64px',fontWeight:600,lineHeight:'1.04em',letterSpacing:'-2.6px',textColor:'#333B38'});
text('description','heroCopy','Connect your store, compare carrier rates, and manage every shipment in one place. Use our partner network, your own contracts, or both.',{fontSize:'18px',lineHeight:'1.65em',textColor:'#68736F'});
frame('heroButtons','heroCopy',{stackDirection:'horizontal',stackAlignment:'center',gap:'12px',width:'auto',overflow:'visible'});button('primaryCta','heroButtons','Start shipping','https://app.zineps.com/Account/Register');icon('ctaArrow','primaryCta','Arrow Right',{$control__color:'#173B35'});button('partnerCta','heroButtons','I’m a logistics partner','https://www.zineps.com/logistics-operating-system',false);
text('supportLine','heroCopy','One dashboard. One API. Your entire shipping network.',{fontSize:'12px',textColor:'#7A8580'});
frame('productStage','hero',{name:'Actual Zineps product and quiet routing',width:'1fr',gap:'30px',overflow:'visible'});
frame('dashboardFrame','productStage',{name:'Original dashboard window',width:'1fr',padding:'6px',radius:'12px',fill:'#FFFFFF',border:'1px solid #DEE9E5','boxShadows.0':'0px 24px 56px 0px rgba(30,70,57,0.10)',overflow:'clip'});
frame('dashboard','dashboardFrame',{name:'Real Zineps dashboard — original SVG',width:'1fr',height:'auto',aspectRatio:1429/982,fill:'https://www.zineps.com/zineps-dashboard.svg',altText:'Zineps dashboard with sidebar navigation, open orders, status cards and an order table',radius:'7px'});
frame('routing','productStage',{name:'Reserved logistics network composition',width:'1fr',height:'76px',stackDirection:'horizontal',stackAlignment:'center',stackDistribution:'center',gap:'16px',overflow:'visible',opacity:0.65});
text('merchant','routing','Your store',{width:'auto',fontSize:'11px',textColor:'#66867C'});
frame('routeA','routing',{width:'42px',height:'1px',fill:'#B0D8CB'});
frame('routeHub','routing',{width:'34px',height:'34px',radius:'100px',fill:'#EAF7F2',border:'1px solid #A0D5C5',stackAlignment:'center',stackDistribution:'center'});frame('routeHubDot','routeHub',{width:'8px',height:'8px',radius:'100px',fill:'#70CAB9'});
frame('routeB','routing',{width:'42px',height:'1px',fill:'#B0D8CB'});
frame('carriers','routing',{width:'auto',gap:'8px'});['DHL','DPD','More carriers'].forEach((label,i)=>text('carrier'+i,'carriers',label,{width:'auto',fontSize:'10px',textColor:'#66867C'}));
frame('routeC','routing',{width:'32px',height:'1px',fill:'#B0D8CB'});text('customer','routing','Your customer',{width:'auto',fontSize:'11px',textColor:'#66867C'});
set('augiA20Il',{'metadata.title':'Zineps — One intelligent shipping platform','metadata.description':'Connect your store, compare carrier rates and manage every shipment in one place with Zineps.','metadata.noIndex':true});
state.phase1Result=await framer.agent.applyChanges(commands.join('\n'),{pagePath:'/'});
state.phase1Ids=state.phase1Result.renamedIds;
console.log(state.phase1Result);
